### ISSUE TITLE
Git URL issue

### ISSUE THREAD

**Issue by rizo** [smondet/dev-opam-repo#1]
(This is related to: https://github.com/hammerlab/ketrew/pull/183)

When installing ketrew, after adding the repo, here's what happens:

```
Downloading archive of ketrew.master...
[ketrew] Fetching git@github.com:hammerlab/ketrew
# opam-version 1.2.0
# os           darwin
# command      git fetch -q origin +HEAD:refs/remotes/opam-ref
# path         /Users/rizo/.opam/packages.dev/ketrew.master
# exit-code    128
# env-file     /Users/rizo/.opam/log/log-6110-42bb52.env
# stdout-file  /Users/rizo/.opam/log/log-6110-42bb52.out
# stderr-file  /Users/rizo/.opam/log/log-6110-42bb52.err
### stderr ###
# Permission denied (publickey).
# fatal: Could not read from remote repository.
#
# Please make sure you have the correct access rights
# and the repository exists.
```

The opam url file should not use SSH for Git, i.e, `git@github.com:hammerlab/ketrew`, but HTTPS instead. It may work for you, since your ssh key is associated to the repo, but public access is only possible over HTTPS, AFAIK.

After changing the url to HTTPS I was able to start the installation. But it failed on later stages due to some type error (See full log [here](https://gist.github.com/rizo/1e6ea92ae45201326828)).

So I guess it's too early to start testing ketrew :P

**Comment by smondet** [comment]
OK, when read-only, HTTPS may be better.

About your error, Ketrew's master branch depends on the master branch of `ppx_deriving_yojson`
(it contains the fix of this issue: https://github.com/whitequark/ppx_deriving_yojson/issues/24).
You should 

```
opam pin add pxx_deriving_yojson https://github.com/whitequark/ppx_deriving_yojson.git
```

`ketrew:master` is a moving target, especially regarding installation, but we use it everyday, happy to answer any question.

Thanks for the feedback !
